# Generated by Django 4.2.4 on 2023-10-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferst_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('coment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='LogMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing', models.DateTimeField(auto_now_add=True, verbose_name='Последняя рассылка')),
                ('status_try', models.CharField(choices=[('ok', 'успешно'), ('faild', 'ошибка')], max_length=20, verbose_name='Статус попытки')),
                ('answer_mail_server', models.BooleanField(blank=True, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('start_time', models.TimeField(verbose_name='Начало рассылки')),
                ('end_time', models.TimeField(verbose_name='Конец срассылки')),
                ('period', models.CharField(choices=[('dally', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесечно')], default='dally', max_length=50, verbose_name='Дата рассылки')),
                ('status', models.CharField(blank=True, choices=[('create', 'создана'), ('started', 'запущена'), ('done', 'завершена')], default='create', max_length=50, null=True, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MessageMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема Расслыки')),
                ('body', models.TextField(verbose_name='Текста рассылки')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
